### ISSUE TITLE
自动生成配置文件的疑惑

### ISSUE THREAD

**Issue by gxianglong** [gaoxianglong/kratos#2]
自动生成配置文件，其中有一个选项

```Java
c_xml.setUrl("jdbc:mysql://192.168.1.1:3306/db");
```

如果我的数据库有多个，都是以testDb_0000——1024这样分布的，这个属性怎么填写？？？？？

**Comment by gaoxianglong** [comment]
其实这个你试一试就知道，setUrl("jdbc:mysql://192.168.1.1:3306/db");只需要指定数据库前缀，在生成配置文件时，会自动补全后缀，这里的数据库名称“db”仅仅只是前缀。<br>
究竟生成多少个数据源，根据setDbSize("16")而定。

**Comment by gxianglong** [comment]
生成一主一从数据源配置文件的时候，主库16个，从库16个，那么属性<br>

```Java
/* master数据源索引起始 */
 c_xml.setDataSourceIndex(1);
/* master配置分库分片信息 */
 c_xml.setDbSize("16");
/* slave数据源索引起始 */
c_xml.setDataSourceIndex(17);
/* slave配置分库分片信息 */
c_xml.setDbSize("16");
```

我没看懂是什么意思？
